Add ca64 assembler, improved errors + .BYTE support
bgourlie/asm6502 pull request #12
Opened 2022-06-26 11:01 UTC by rib

Ideally this could have been split into a few patches, but still I figured I'd share some of the changes I recently made in case they are useful to others...

The changes this patch makes are:
1. Add a standalone `ca65` assembler tool
2. Switches to parsing input as a &str instead of &[u8] so it's possible to use nom's `convert_error` utility for formatting `VerboseError`s
3. Adds a custom `AssembleError` (using `thiserror` crate) that can explicitly report errors with tokenizing, parsing or IO (instead of just returning a String)
4. Uses `VerboseError` for tracking nom errors with context, to get more insightful error messages
5. Adds support for `;` based comments
6. Starts adding support for compiler directives, with support for a `.BYTE` / `.DB` directive that can be used to insert raw bytes into the assembly

_Note: The parser now only looks for / allows a single instruction per-line
Note: This removes support for labels that don't have a colon_

2022-06-30 02:48 UTC, bgourlie commented
Looks good to me, but want to ping @myxo for review as well since he's been contributing lately.

2022-06-30 06:29 UTC, myxo commented
I'll review it on the weekend

2022-07-02 09:09 UTC, myxo requested changes
Basically I want unit tests for new parsed objects and clarification about `input` var in `assembler/mod.rs`
Otherwise it looks great. New error messages are helpful.

2022-07-02 09:09 UTC, myxo commented on Cargo.toml
> +name="as65"
I like the name =)

2022-07-02 09:09 UTC, myxo commented on src/parser/mod.rs
> +pub fn end_of_line_comment(input: &str) -> Result<Option<&str>>
Can you add a unit test for comments?

2022-07-02 09:09 UTC, myxo commented on src/parser/mod.rs
> +{
Code style is a little different. I would suggest to run `cargo fmt`, maybe as separate commit

2022-07-02 09:09 UTC, myxo commented on src/parser/mod.rs
> +}
Also, can you add unit tests for .BYTE and .DB?

2022-07-02 09:09 UTC, myxo commented on src/assembler/mod.rs
>  }
Why you pass `input` everywhere if you don't use it?

2022-07-02 09:09 UTC, myxo commented on src/parser/tests.rs
> -fn single_label_no_colon() {
Do not delete this test, just `#[ignore]` it. Maybe I'll return to it at some point and make it work.

2022-07-02 10:16 UTC, rib commented on src/assembler/mod.rs
>  }
I think the error needed the lifetime of the input, so it was a way of satisfying that

2022-07-02 12:18 UTC, rib commented
Okey, the updated branch hopefully addresses all the above comments. It adds unit tests for comments + the .byte/.db commands, fixes the braces for end_of_line_comment and also runs `cargo fmt` in a follow up patch.

After adding unit tests for comments I also ended up updating the support to handle lines that only have a comment (previously it was only handling comments after an instruction or label)

About passing `input` around; the commit message has a note about this this:
> For the sake of passing the required lifetime needed for
> VerboseErrors then parsing code is now also given a reference
> to the original input.

2022-07-02 12:19 UTC, rib commented
(oh, and I re-instated the `single_label_no_colon` test with an `#[ignore]` directive)

2022-07-02 12:57 UTC, myxo approved these changes
Ok, LGTM.
Thanks for PR!

2022-07-02 12:57 UTC, myxo commented on src/parser/tests.rs
> +    let parsed_db = super::parse_lines(&asm);
I'll assume this was the intension 
```suggestion
    let asm_byte = ".BYTE $4E, $45, $53, $1A";
    let asm_db = ".DB $4E, $45, $53, $1A";
    let parsed_bytes = super::parse_lines(&asm_byte);
    let parsed_db = super::parse_lines(&asm_db);
```

2022-07-02 13:00 UTC, merged